const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={page:'dashboard',csrf:'',role:'owner',data:null,memoryLayer:'short',eventSource:null};
const canWrite=()=>state.role==='owner';
const fa=n=>new Intl.NumberFormat('fa-IR').format(Number(n)||0),tech=v=>`<span class="tech" dir="ltr">${esc(v??'—')}</span>`;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(text){const e=$('#toast');e.textContent=text;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3200)}
async function api(path,o={}){const h={'Content-Type':'application/json',...(o.headers||{})};if(state.csrf)h['X-CSRF-Token']=state.csrf;const r=await fetch('/api'+path,{credentials:'include',...o,headers:h});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw Error(d?.error||`HTTP ${r.status}`);return d}
function loading(){return '<div class="loading-grid">'+[1,2,3,4].map(()=>'<i></i>').join('')+'</div>'}
function toolbar(extra=''){return `<div class="data-toolbar"><label>جستجو<input id="filter-q" placeholder="عبارت، شناسه یا trace_id"></label>${extra}<button class="small-button" id="apply-filter">اعمال فیلتر</button></div>`}
function table(items,cols,detail=''){if(!items?.length)return '<div class="empty-state"><strong>داده‌ای ثبت نشده است</strong><span>این نتیجه مستقیماً از Backend خوانده شده و داده نمایشی وجود ندارد.</span></div>';return `<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${c[1]}</th>`).join('')}${detail?'<th>عملیات</th>':''}</tr></thead><tbody>${items.map(r=>`<tr>${cols.map(c=>`<td data-label="${c[1]}">${format(r[c[0]],c[0])}</td>`).join('')}${detail?`<td><button class="row-action" data-detail="${detail}" data-id="${esc(r.id??r.memory_id??r.event_id??r.job_id)}">جزئیات</button></td>`:''}</tr>`).join('')}</tbody></table></div>`}
function format(v,k){if(v===null||v===undefined||v==='')return '—';if(/(_id|trace|model|provider|path|run_id|job_id|memory_id|event_id)$/.test(k))return tech(v);if(/(_at|timestamp|last_seen|created_at|updated_at)$/.test(k)&&Number(v))return `<span class="tech" dir="ltr">${new Date(Number(v)*1000).toLocaleString('fa-IR')}</span>`;if(typeof v==='object')return tech(JSON.stringify(v));return esc(String(v).slice(0,220))}
function head(title,desc,badge='LIVE DATA'){return `<div class="hero-row"><div><h3>${title}</h3><p>${desc}</p></div><span class="live-badge">${badge}</span></div>`}
function cards(entries){return `<div class="section-grid">${entries.map(([t,v,s])=>`<section class="section-card glass"><span class="tag">${esc(s||'STATUS')}</span><h3>${esc(t)}</h3><p>${format(v,'value')}</p></section>`).join('')}</div>`}
function stat(label,value,foot,icon,glow){return `<article class="stat-card glass" style="--glow:${glow}"><span class="stat-label">${label}</span><strong class="stat-value">${esc(value)}</strong><span class="stat-foot">${foot}</span><span class="stat-icon">${icon}</span></article>`}
function dashboard(d){const s=d.status||{},p=d.provider||{};return `${head('نمای زنده مأموریت','وضعیت عملیاتی Zero؛ به‌روزرسانی محدود از مسیر SSE.','LIVE STREAM')}<div class="stats-grid">${stat('وضعیت Zero',s.listener?'آنلاین':'آفلاین','Listener','◉','#4de5b0')}${stat('پردازنده',s.cpu||'—','Load average','◌','#6b8cff')}${stat('حافظه RAM',s.ram||'—','مصرف فعلی','◈','#a779ff')}${stat('فضای دیسک',s.disk||'—','فضای آزاد','◇','#4de5ef')}</div>${cards([['Provider فعال',p.active,'ROUTER'],['مدل فعال',p.model,'MODEL'],['Session امن','فعال','SECURITY']])}<section class="panel-card glass activity"><div class="panel-head"><h3>فعالیت اخیر</h3><span>${fa(d.activity?.length)} رویداد</span></div>${table(d.activity||[],[['event','رویداد'],['timestamp','زمان']])}</section>`}
async function renderChat(){const q=$('#filter-q')?.value||'';const d=await api('/chats?q='+encodeURIComponent(q));return head('گفتگوها','نمای read-only؛ ارسال پیام و حذف چون Backend امنی ندارند عمداً ارائه نشده است.','READ ONLY')+toolbar()+table(d.items,[['id','شناسه'],['chat_id','چت'],['sender_id','فرستنده'],['sender_label','نام'],['role','نوع'],['text','پیام'],['created_at','زمان'],['trace_id','Trace']],'/chats')+`<p class="result-count">${fa(d.total)} پیام</p>`}
const memTabs=['short','medium','long','semantic','semantic-candidates','experience','experience-candidates','procedural','procedural-candidates','world','world-relations'];
async function renderMemory(){const d=await api(`/memory/${state.memoryLayer}`);const cols=Object.keys(d.items[0]||{}).filter(x=>!x.endsWith('_json')).slice(0,7).map(x=>[x,x]);return head('حافظه','لایه‌ها جدا، scoped و مطابق Permissionهای موجود Backend هستند.')+`<div class="tabs">${memTabs.map(x=>`<button class="tab ${x===state.memoryLayer?'active':''}" data-layer="${x}">${x}</button>`).join('')}</div>`+toolbar(`<label>وضعیت<select id="status-filter"><option value="">همه</option><option>active</option><option>pending</option><option>verified</option><option>invalidated</option></select></label>`)+table(d.items,cols,`/memory/${state.memoryLayer}`)+`<p class="result-count">${fa(d.total)} مورد</p>`}
async function renderKnowledge(){const d=await api('/knowledge');return head('دانش','Worker، اجراها، منابع و صف‌ها از Storage واقعی Zero.')+cards([['وضعیت Worker',d.status?.running?'در حال اجرا':'آماده','WORKER'],['Backend',d.status?.backend||d.schedule?.backend||'—','BACKEND'],['صف وب',JSON.stringify(d.web_queue),'QUEUE'],['صف تلگرام','Archived / Paused','ARCHIVED']])+`<section class="panel-card glass"><div class="panel-head"><h3>Knowledge Items</h3><button class="danger-button" id="knowledge-run">اجرای محدود Dry-run</button></div>${table(d.items.items,[['id','ID'],['title','عنوان'],['status','وضعیت'],['confidence','اعتماد'],['last_verified_at','آخرین تأیید']],'/knowledge/items')}</section><section class="panel-card glass activity"><div class="panel-head"><h3>تاریخچه اجرا</h3></div>${table(d.runs.items,[['run_id','Run'],['status','وضعیت'],['backend','Backend'],['accepted_count','پذیرفته'],['rejected_count','ردشده'],['started_at','شروع']])}</section>`}
async function renderRouter(){const d=await api('/router');return head('مدل‌ها و Router','کلیدها فقط با شناسه امن نمایش داده می‌شوند؛ مقدار credential هرگز از API خارج نمی‌شود.')+cards([['Provider فعال',d.active,'PRIMARY'],['Fallback',d.fallback.join(' → '),'CHAIN'],['استراتژی',d.strategy,'ROUTER'],['Google Grounding',d.google_grounding?'فعال':'غیرفعال','SEARCH']])+d.providers.map(p=>`<section class="panel-card glass activity"><div class="panel-head"><h3>${esc(p.name)}</h3><span>${tech(p.model)}</span></div>${table(p.key_pool,[['id','شناسه امن'],['healthy','Healthy'],['cooldown','Cooldown']])}<p class="result-count">Healthy: ${fa(p.healthy_keys)} · Cooldown: ${fa(p.cooldown_keys)} · Quota: ${esc(p.quota_scope)}</p></section>`).join('')}
async function renderLogs(){const q=$('#filter-q')?.value||'';const d=await api('/logs?size=100&trace_id='+encodeURIComponent(q));return head('لاگ‌ها','خروجی redacted؛ Token، credential و رشته‌های حساس قبل از ارسال حذف می‌شوند.','REDACTED')+toolbar(`<label>سطح<select id="level-filter"><option value="">همه</option><option>ERROR</option><option>WARNING</option><option>INFO</option></select></label><a class="small-button" href="/api/logs/download">دانلود امن</a>`)+`<div class="log-view">${d.items.map(x=>`<div><time>${esc(x.timestamp)}</time><b>${esc(x.component)}</b><code dir="ltr">${esc(x.line)}</code></div>`).join('')||'<p>رویدادی مطابق فیلتر نیست.</p>'}</div>`}
async function renderJobs(){const d=await api('/jobs');return head('Jobها','وضعیت واقعی Template Jobs؛ عملیات حساس Owner-only و نیازمند Confirmation.')+table(d.items,[['job_id','Job'],['title','عنوان'],['state','وضعیت'],['approval_state','تأیید'],['next_run_at','اجرای بعدی'],['last_run_at','آخرین اجرا']],'/jobs')+`<section class="panel-card glass activity"><div class="panel-head"><h3>Runهای اخیر</h3></div>${table(d.runs.items,[['run_id','Run'],['job_id','Job'],['state','وضعیت'],['trace_id','Trace'],['created_at','زمان']])}</section>`}
async function renderUsers(){const d=await api('/users'),s=await api('/sessions');return head('کاربران و Sessionها','فقط داده‌های موجود Zero؛ هیچ اطلاعات خصوصی جدیدی جمع‌آوری نمی‌شود.')+cards([['Owner',`@${d.owner.username}`,'OWNER'],['کاربران شناخته‌شده',d.known.length,'USERS'],['Sessionهای فعال',s.items.length,'SESSIONS']])+`<section class="panel-card glass activity"><div class="panel-head"><h3>کاربران شناخته‌شده</h3></div>${table(d.known,[['user_id','کاربر'],['chat_id','چت'],['label','نام'],['message_count','پیام'],['last_seen','آخرین فعالیت']])}</section><section class="panel-card glass activity"><div class="panel-head"><h3>Sessionهای ورود</h3><button id="logout-all" class="danger-button">ابطال همه Sessionها</button></div>${table(s.items,[['id','Session'],['username','کاربر'],['created_at','ایجاد'],['last_seen','آخرین فعالیت'],['expires','انقضا']])}</section>${table(d.login_history,[['event','رویداد'],['user_id','کاربر'],['timestamp','زمان']])}`}
async function renderSettings(){const d=await api('/settings'),groups=Object.entries(d.config);return head('تنظیمات','فقط overrideهای allowlist شده قابل تغییرند؛ Secretها تنها به‌صورت وضعیت.')+`<div class="section-grid">${groups.map(([k,v])=>`<section class="section-card glass"><span class="tag">${esc(k)}</span><h3>${esc(k)}</h3><pre class="json-view" dir="ltr">${esc(JSON.stringify(v,null,2))}</pre></section>`).join('')}</div><section class="panel-card glass activity"><div class="panel-head"><h3>وضعیت Secretها</h3></div>${table(Object.entries(d.secrets).map(([name,v])=>({name,...v})),[['name','Secret'],['configured','Configured'],['permission_valid','Permission'],['last_rotated','Last rotated']])}</section><section class="panel-card glass activity"><div class="panel-head"><h3>Overrideهای قابل ویرایش</h3></div>${d.editable.map(k=>`<div class="setting-row"><span>${tech(k)}</span><input data-setting="${esc(k)}" value="${esc(d.overrides[k]??'')}"><button class="row-action save-setting" data-key="${esc(k)}">ذخیره</button></div>`).join('')}</section>`}
const titles={dashboard:'داشبورد عملیاتی',chat:'گفتگوها',memory:'حافظه',knowledge:'دانش',models:'مدل‌ها و Provider',logs:'لاگ‌ها',jobs:'Jobها',users:'کاربران و Sessionها',settings:'تنظیمات'};
async function render(){const p=$('#page');$('#page-title').textContent=titles[state.page];p.innerHTML=loading();try{let h;if(state.page==='dashboard')h=dashboard(await api('/dashboard'));else if(state.page==='chat')h=await renderChat();else if(state.page==='memory')h=await renderMemory();else if(state.page==='knowledge')h=await renderKnowledge();else if(state.page==='models')h=await renderRouter();else if(state.page==='logs')h=await renderLogs();else if(state.page==='jobs')h=await renderJobs();else if(state.page==='users')h=await renderUsers();else h=await renderSettings();p.innerHTML=h;bindPage()}catch(e){p.innerHTML=`<div class="empty-state error"><strong>خطا در دریافت داده واقعی</strong><span>${esc(e.message)}</span></div>`}}
function modal(title,data,actions=''){let m=$('#detail-modal');if(!m){m=document.createElement('dialog');m.id='detail-modal';m.className='detail-modal glass';document.body.append(m)}m.innerHTML=`<div class="modal-head"><h3>${esc(title)}</h3><button id="close-modal">×</button></div><pre class="json-view" dir="ltr">${esc(JSON.stringify(data,null,2))}</pre>${actions}`;m.showModal();$('#close-modal').onclick=()=>m.close()}
async function openDetail(path,id){try{const d=await api(`${path}/${encodeURIComponent(id)}`);let actions='';if(path.startsWith('/memory/'))actions='<div class="modal-actions"><button class="row-action memory-op" data-action="verify">تأیید صحت</button><button class="row-action memory-op" data-action="approve">Approve</button><button class="danger-button memory-op" data-action="invalidate">Invalidate</button><button class="danger-button memory-op" data-action="deprecate">Deprecate</button></div>';if(path==='/jobs')actions='<div class="modal-actions"><button class="row-action job-op" data-action="resume">Resume</button><button class="danger-button job-op" data-action="pause">Pause</button></div>';modal(`جزئیات ${id}`,d,actions);$$('.memory-op').forEach(b=>b.onclick=()=>confirmed(`${path}/${id}/${b.dataset.action}`,b.dataset.action));$$('.job-op').forEach(b=>b.onclick=()=>confirmed(`${path}/${id}/${b.dataset.action}`,b.dataset.action))}catch(e){toast(e.message)}}
async function confirmed(path,label){if(!confirm(`عملیات ${label} اجرا شود؟`))return;try{await api(path,{method:'POST',body:JSON.stringify({confirm:true,reason:'web_panel'})});toast('عملیات ثبت شد.');$('#detail-modal')?.close();render()}catch(e){toast(e.message)}}
function bindPage(){
 if(!canWrite()) $$('.danger-button,.save-setting,#knowledge-run,#logout-all,.memory-op,.job-op').forEach(x=>x.remove());
 $$('.row-action[data-detail]').forEach(b=>b.onclick=()=>openDetail(b.dataset.detail,b.dataset.id));
 $$('.tab[data-layer]').forEach(b=>b.onclick=()=>{state.memoryLayer=b.dataset.layer;render()});
 $('#apply-filter')?.addEventListener('click',render);
 $('#knowledge-run')?.addEventListener('click',()=>confirmed('/knowledge/run','dry-run محدود'));
 $('#logout-all')?.addEventListener('click',()=>confirmed('/auth/logout-all','ابطال همه Sessionها'));
 $$('.save-setting').forEach(b=>b.onclick=async()=>{const i=$(`[data-setting="${b.dataset.key}"]`);let v=i.value;if(v==='true'||v==='false')v=v==='true';try{await api('/settings/'+b.dataset.key,{method:'POST',body:JSON.stringify({value:v})});toast('تنظیم ذخیره شد.')}catch(e){toast(e.message)}})
}
function connectRealtime(){state.eventSource?.close();if(state.page!=='dashboard')return;state.eventSource=new EventSource('/api/realtime');state.eventSource.onmessage=e=>{try{const d=JSON.parse(e.data);$('#latency').textContent='SSE';const cardsEl=$('.stats-grid');if(cardsEl)cardsEl.outerHTML=`<div class="stats-grid">${stat('وضعیت Zero',d.status.listener?'آنلاین':'آفلاین','Listener','◉','#4de5b0')}${stat('پردازنده',d.status.cpu,'Load average','◌','#6b8cff')}${stat('حافظه RAM',d.status.ram,'مصرف فعلی','◈','#a779ff')}${stat('فضای دیسک',d.status.disk,'فضای آزاد','◇','#4de5ef')}</div>`}catch{}}}
async function showApp(animated=true){$('#login').classList.add('hidden');if(animated&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const tr=$('#entry-transition'),texts=['Connecting to Zero Core','Loading Memory','Opening Control Center'];tr.classList.remove('hidden');for(const t of texts){$('#transition-text').textContent=t;await new Promise(r=>setTimeout(r,650));if(tr.classList.contains('hidden'))break}tr.classList.add('hidden')}$('#app').classList.remove('hidden');render();connectRealtime()}
async function boot(){try{const me=await api('/auth/me');state.csrf=me.csrf;state.role=me.role||'viewer';$('#operator-name').textContent=me.username||'مالک سیستم';showApp(false)}catch{initSpace()}}
async function initSpace(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;try{const THREE=await import('/panel/three.module.min.js');const canvas=$('#space-canvas'),renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:false,powerPreference:'low-power'}),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(60,innerWidth/innerHeight,.1,100);camera.position.z=7;const geo=new THREE.BufferGeometry(),count=innerWidth<700?320:700,pos=new Float32Array(count*3);for(let i=0;i<pos.length;i++)pos[i]=(Math.random()-.5)*24;geo.setAttribute('position',new THREE.BufferAttribute(pos,3));scene.add(new THREE.Points(geo,new THREE.PointsMaterial({color:0x80cfff,size:.035})));const planet=new THREE.Mesh(new THREE.SphereGeometry(1.1,24,16),new THREE.MeshBasicMaterial({color:0x182c62,wireframe:true}));planet.position.set(-3,-1,-1);scene.add(planet);let active=true;function size(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}size();addEventListener('resize',size);function tick(){if(!active)return;geo.rotateY(.0006);planet.rotateY(.003);renderer.render(scene,camera);requestAnimationFrame(tick)}tick();$('#skip-animation').onclick=()=>{active=false;canvas.classList.add('hidden')}}catch{document.body.classList.add('space-fallback')}}
$('#request-form').onsubmit=async e=>{e.preventDefault();try{await api('/auth/request',{method:'POST',body:JSON.stringify({identity:$('#identity').value.trim()})});$('#request-form').classList.add('hidden');$('#verify-form').classList.remove('hidden');$('#otp').focus();toast('کد در تلگرام ارسال شد.')}catch(x){toast(x.message)}};
$('#verify-form').onsubmit=async e=>{e.preventDefault();try{const r=await api('/auth/verify',{method:'POST',body:JSON.stringify({identity:$('#identity').value.trim(),code:$('#otp').value.trim()})});state.csrf=r.csrf;state.role=r.role||'viewer';showApp(true)}catch(x){toast(x.message)}};
$('#back-login').onclick=()=>{$('#verify-form').classList.add('hidden');$('#request-form').classList.remove('hidden')};$('#skip-transition').onclick=()=>$('#entry-transition').classList.add('hidden');$('#logout').onclick=async()=>{try{await api('/auth/logout',{method:'POST'})}finally{location.reload()}};$('#collapse').onclick=()=>$('#sidebar').classList.toggle('collapsed');$('#mobile-menu').onclick=()=>$('#sidebar').classList.toggle('mobile-open');$$('.nav-item').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===b));$('#sidebar').classList.remove('mobile-open');render();connectRealtime()});boot();
